version: "2"
plugins:
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
  pmd:
    enabled: true
    config:
      rulesets:
        - category/java/codestyle.xml
        - category/java/bestpractices.xml
  duplication:
    enabled: true
    config:
      languages:
        java:
          threshold: 25
exclude_patterns:
  - "**/test/**"
  - "**/vendor/**"
